blank_issues_enabled: true
contact_links:
  - name: Ask Bluefin
    url: https://github.com/ublue-os/bluefin/discussions/categories/ask-bluefin
    about: Ask our trained raptor questions about Bluefin
  - name: Questions and Feedback
    url: https://github.com/ublue-os/bluefin/discussions
    about: Share tips and help others
